version: '3.8'

# GPU部署配置 - 支持NVIDIA CUDA加速
# 需要安装nvidia-docker2

networks:
  audio2sub_network_gpu:
    driver: bridge

volumes:
  redis_data_gpu:

services:
  redis:
    image: redis:7-alpine
    container_name: audio2sub_redis_gpu
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data_gpu:/data
    networks:
      - audio2sub_network_gpu
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    container_name: audio2sub_backend_gpu
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
    environment:
      - DEPLOYMENT_MODE=docker
      - WHISPER_DEVICE=cuda
      - WHISPER_COMPUTE_TYPE=float16
      - NVIDIA_VISIBLE_DEVICES=all
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - audio2sub_network_gpu
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    container_name: audio2sub_worker_gpu
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
    environment:
      - DEPLOYMENT_MODE=docker
      - WHISPER_DEVICE=cuda
      - WHISPER_COMPUTE_TYPE=float16
      - NVIDIA_VISIBLE_DEVICES=all
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - audio2sub_network_gpu
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: celery -A celery_app worker --loglevel=info --concurrency=1
    healthcheck:
      test: ["CMD", "celery", "-A", "celery_app", "inspect", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  flower:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    container_name: audio2sub_flower_gpu
    restart: unless-stopped
    ports:
      - "5555:5555"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - audio2sub_network_gpu
    command: celery -A celery_app flower --port=5555
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
