version: '3.8'

# 原生部署配置 - 仅启动Redis，应用直接在宿主机运行
# 用于开发环境和需要最佳性能的场景

networks:
  audio2sub_network_native:
    driver: bridge

volumes:
  redis_data_native:

services:
  redis:
    image: redis:7-alpine
    container_name: audio2sub_redis_native
    restart: unless-stopped
    ports:
      - "16379:6379"  # 使用非标准端口避免冲突
    volumes:
      - redis_data_native:/data
    networks:
      - audio2sub_network_native
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3
